import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Matrox S.A.",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="es"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col  ">
        <nav className="bg-zinc-800 bg-cover  bg-no-repeat">
          <div className="bg-black/15 w-full h-full  text-background items-center justify-between flex px-5">
            <div className="justify-self-start flex items-center gap-2">
              <Image
                src="/Matrox.png"
                alt="Next.js Logo"
                width={70}
                height={70}
                className="object-contain p-2"
              />
            </div>

            <div className="font-semibold flex gap-8 justify-self-center">
              <Link
                href={"/"}
                className="  px-4  py-2 rounded-xl text-amber-50  bg-gray-500/50 transition delay-150 duration-300 ease-in-out hover:-translate-y-2 hover:scale-110 hover:bg-indigo-900/50"
              >
                Home
              </Link>
              <Link
                href={"/about"}
                className=" px-4  py-2 rounded-xl text-amber-50  bg-gray-500/50 transition delay-150 duration-300 ease-in-out hover:-translate-y-2 hover:scale-110 hover:bg-indigo-900/50"
              >
                About
              </Link>
              <Link
                href={"/hero"}
                className=" px-4  py-2 rounded-xl text-amber-50  bg-gray-500/50 transition delay-150 duration-300 ease-in-out hover:-translate-y-2 hover:scale-110 hover:bg-indigo-900/50"
              >
                Hero
              </Link>
              <Link
                href={"/login"}
                className=" px-4  py-2 rounded-xl text-amber-50  bg-gray-500/50 transition delay-150 duration-300 ease-in-out hover:-translate-y-2 hover:scale-110 hover:bg-indigo-900/50"
              >
                Login
              </Link>
            </div>
          </div>
        </nav>

        {children}

        <footer className="pt-5 border-t border-white/80 flex bg-zinc-800 justify-between gap-8 items-center mt-auto">
          <div className=" p-8 flex gap-8 text-gray-400 text-sm font-medium">
            <div className="flex flex-col">
              <span className="text-white text-xl font-bold">100%</span>
              <span>Compromiso</span>
            </div>
            <div className="flex flex-col">
              <span className="text-white text-xl font-bold">Next.js</span>
              <span>Tecnología</span>
            </div>
          </div>
          <div className="flex flex-col py-7 ">
            <h1 className="text-xl ">Matrox S.A. </h1>
            <span className="bg-clip-text text-transparent bg-linear-to-r from-blue-300 to-red-400">
              Todos los derechos reservados a Matrox S.A. &copy; 2026
            </span>
          </div>

          <div className="flex items-center justify-center p-6">
            <div className="bg-linear-to-b from-cyan-600/40 via-violet-400/20 to-transparent rounded-full p-6">
              <Image
                src="/Matrox.png"
                alt="Next.js Logo"
                width={80}
                height={80}
                className="object-contain"
              />
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
